task_batches ={
  "Project Management Tools and Templates": [
    "Requirements List",
    "Gaps List",
    "Issue Management Plan and Issues List",
    "Scope Management Plan and Scope Change Templates",
    "Decision Log",
    "Communications Plan",
    "Steering Committee Presentation Templates",
    "High-Level Project Schedule",
    "Project Team Calendar",
    "Task Plan",
    "Individual Work List",
    "Daily Huddle List",
    "WRICEF Tracking Plan",
    "Data Migration Tracking Plan",
    "EDI Tracking",
    "Project Dashboard",
    "Risk Analysis/Mitigation Plan",
    "Testing Strategy Template",
    "Phase Sign-Off Process"
  ],
  "Quality Reviews": [
    "Deliverable Reviews",
    "Q-Gate Reviews"
  ],
  "Data Migration Approach": [
    "Complexity Assessment",
    "Confirm and Plan",
    "Data Mapping",
    "Development",
    "Refine",
    "Extract and Transform",
    "Pre-validation",
    "Load",
    "Post-validation",
    "Correct",
    "Cleanse",
    "Harmonize",
    "Data Cycles"
  ],
  "Embedded Analytics": [
    "Workshops across the various functional areas to help identify out-of-box Embedded Analytics Fiori-based reports to be leveraged.",
    "Identification of potential customizations relative to Fiori reports.",
    "Customization of ten 10| Fiori-based reports."
  ],
  "Analytics: S/4HANA Data Integration to Existing MS Azure based Landscape": [
    "Identify S/4 sources table/views to for use with the current Data Liberator/SLT based integration with the current MS Azure based target database.",
    "Data to be replicated in same manner as ECC",
    "CDS view modification to support replication process as needed.",
    "Provide guidance to Client resources relative to SAP considerations as needed."
  ],
  "SAP Analytics Cloud SAC| Implementation w/ or w/out Datasphere DSP|": [
    "SAC and DSP tenant set-up as applicable|",
    "SAC Cloud Connector/DPA set-up as applicable|",
    "Establish required source system integration",
    "Detailed blueprint of solution",
    "DSP and/or SAC based model development to support stories noted below|",
    "12 twelve| developed stories Dashboard/Visualizations/Excel|",
    "Security configuration",
    "Formal system/integration testing"
  ],
  "Technical Development of Workflows, Reports, Interfaces, Conversions, Enhancements, Forms WRICEF| and Electronic Data Interface EDI|": [
    "Functional specification - Voice of Customer",
    "Agreement on scope for WRICEF object",
    "Unit Test",
    "Final Acceptance Test",
    "Testing"
  ],
  "PREP": [
    "Contract Signature",
    "Standard onboarding activities",
    "Self Enablement",
    "Project Initiation",
    "Project Organization Structure",
    "Project Plan",
    "Project Kickoff and Onboarding",
    "S/4HANA Public Cloud Learning Enablement for Client Team",
    "Project Portal",
    "System Provisioning and Solution Activation",
    "Phase Closure and Signoff Phase Deliverables",
    "Q-Gate review of Prep Phase"
  ],
  "EXPLORE": [
    "Validation",
    "Organization Structure Workshop and Data Education",
    "High Level Value Chain Scenarios",
    "Fit to Standard Workshops",
    "Gap Validation, Finalize Scope, Documentation",
    "Extension and Integration Requirements Gathering",
    "Data Migration Requirements Gathering",
    "Capture requirements in SAP CALM",
    "Fill up Business Driven Configuration Questionnaires",
    "Phase Initiation",
    "Project Team Enablement",
    "Testing Strategy Document",
    "Fit To Standard Workshop",
    "Data Migration Strategy",
    "Extension and Integration Strategy",
    "User Access and Security Strategy",
    "Data Mapping Documents",
    "SAP Development and Test Environment Provisioning",
    "Solution Readout",
    "Phase Closure and Signoff Phase Deliverables",
    "Q-Gate review of Deploy Phase"
  ],
  "REALIZE": [
    "Phase Initiation",
    "Plan Realize Phase",
    "Development Stream Kickoff",
    "Build Cycle Initiation Iterative|",
    "Execution, Monitoring and Controlling Results",
    "Configuration",
    "Functional Specifications for In-Scope WRICEF Objects",
    "Technical Specifications for In-Scope WRICEF Objects",
    "Development - WRICEF in SAP",
    "Development - WRICEF in Legacy Systems|",
    "Quality Assurance QA| Environment Setup",
    "User Experience and Security Kickoff",
    "Test Workstream Kickoff to Support Integration Testing",
    "Define Scope for Entrance and Exit Criteria for the Integration Test Cycle",
    "Test Data Preparation for Integration Test Cycle 1",
    "Test Data Preparation for Additional Integration Tests",
    "Integration Test Execution",
    "Integration Test Signoff",
    "Data Mapping Documents",
    "Data Extraction and Transformation SAP source|",
    "Data Extraction and Transformation Non-SAP source|",
    "Data Loads into SAP",
    "Data Validation",
    "User Acceptance Test",
    "Production Environment PRD| Design & Setup",
    "Production Support after Go-Live – Hypercare Phase",
    "EDI003 – 944 Warehouse  Stock Transfer Receipt Advice",
    "EDI004 – 945 Warehouse  Shipping Advice",
    "EDI005 – 947 Warehouse  Inventory Adjustment Advice",
    "EDI011 - 810 Invoice for Vendor",
    "EDI012 - 820 Remittance Advice",
    "EDI014 - 850 Purchase Order from Customer",
    "EDI019 - 812 Credit/Debit Adjustment",
    "INT034 - KWI Orders to EDI",
    "EDI001 – 940 Warehouse  Shipping Order",
    "EDI002 – 943 Warehouse  Stock Transfer Shipment Advice",
    "EDI006 – 810 Invoice for Customer",
    "EDI007 - 846 Inventory Inquiry",
    "EDI008 - 855 Purchase Order Acknowledgement",
    "EDI009 - 856 Advance Ship Notice",
    "EDI030 - 870 Order Status",
    "INT005 - SAP Financials Integration w/ SAP Concur",
    "INT006 - API Connector",
    "ADD04 - Customer Statements",
    "INT012 - Stock Availability",
    "INT013 - Products /Materials Creation",
    "INT036 - Invoice Receipts",
    "INT037 - Stock",
    "INT038 - Goods_movement API",
    "ADD26 - Lockbox BAI2",
    "ADD15 - Order Status Shopify|",
    "ADD14 - Orders Shopify|",
    "INT029 - Material Stock Replication / Inventory",
    "ADD11 - Return/Refund Status",
    "ADD07 - Order Status",
    "ADD10 - Invoice Status",
    "ADD08 - Status Change",
    "ADD01 - Error Handling",
    "INT009 - Order Stimulate Order Change API",
    "INT028 - Sales, Returns, Service Orders",
    "ADD02 - Order Return/Refund",
    "ADD03 - Service Order Notification and Estimates",
    "INT010 - Invoice Report and Pay",
    "ADD12 - Service/Repair Estimates",
    "VASS S11 - Replicate Order Notification from S/4 to Commerce Cloud - NTRFCS-62",
    "VASS S10 - Realtime Invoice History - NTRFCS-55",
    "VASS S1- Material Replication - NTRFCS-48",
    "VASS S2 - Master Data - Business Partner - NTRFCS-41",
    "VASS S4 - Master Data - Stock Replication - NTRFCS-34",
    "VASS S5 - Master Data - Classification Replication - NTFRCS-27",
    "VASS S6 - Transaction Data - Order Replication - NTRFCS-20",
    "VASS S9 - Material Stock Read - NTRFCS-13",
    "VASS S12 - Order Details",
    "Change Impact Analysis",
    "Request SAP S/4 HANA Cloud Development System and Initial Setup",
    "Conduct Initial Access to the Cloud Development System",
    "Request the S/4HANA Cloud Test System",
    "Conduct Initial Access to the Cloud Test System",
    "Request SAP S/4 HANA Cloud Production System Upon closing of the Starter System|",
    "Conduct Initial Access to the Cloud Test System Upon closing of the Starter System|",
    "Manage the Development of Enablement Content",
    "Create Sprint Plans",
    "Configure in-Scope Items",
    "Configure Identity and Access profiles in Development System",
    "Setup Integration on Test System",
    "Develop and Transport Extensions if applicable|",
    "Migrate Data into Development Tenant",
    "Migrate Data into Test Tenant",
    "Configure Analytics & Reports in the Test Tenant",
    "Setup Integrations in Production System",
    "Setup Test Plans",
    "Setup Solution Walkthrough Sessions|",
    "Configure Analytics & Reports in the Production Tenant",
    "Create Cutover/Handover Plan",
    "Define Phase Closure & Sign-Off Process & Criteria",
    "Sprint 1",
    "Sprint 2",
    "Sprint 3",
    "Sprint 4",
    "Sprint 5",
    "Sprint 6",
    "Sprint 7",
    "Sprint 8",
    "Training + UAT",
    "Development Build Cycles",
    "Requirements Gathering",
    "Feasibility",
    "Design",
    "Development",
    "Unit Testing",
    "Sign Off",
    "Functional Configuration",
    "Business Process Validation",
    "Testing",
    "Unit and String Testing",
    "Integration TestsIT Cycles|",
    "User Acceptance Test",
    "Security Test",
    "Test verification checklist validation",
    "IT1 Complete",
    "IT2 Complete",
    "IT3 Complete",
    "UAT Complete",
    "Q-Gate review of Realize Phase",
    "Scope Items",
    "Finance|1EG-Bank Integration with File Interface",
    "Finance|1ZT-Managing Material Price Changes and Inventory Values",
    "Finance| 2JB-SAP Fiori Analytical Apps for Financial Accounting",
    "Finance|2QY-SAP Fiori Analytical Apps for Asset Accounting in Finance ",
    "Finance| 2V7-Monitoring of Goods and Invoice Receipts",
    "Finance|BEG-Standard Cost Calculation",
    "Finance|BEI-Period-End Closing - Plant",
    "Finance|BEJ-Inventory Valuation for Year-End Closing",
    "Finance| BEV-Internal Order - Actual",
    "Finance|BF7-Period-End Closing - Maintenance  Orders",
    "Finance|BFH-Asset Under Construction",
    "Finance| BGC-SAP Fiori Analytical Apps for G/L Accounting in Finance ",
    "Finance| J54-Overhead Cost Accounting",
    "Finance| J58-Accounting and Financial Close",
    "Finance| J59-Accounts Receivable",
    "Finance| J60-Accounts Payable",
    "Finance| J62-Asset Accounting",
    "Manufacturing| 1FM-Quality Management in Procurement ",
    "Manufacturing| 1Y5-Production Operations with Manufacturing  Execution System",
    "Manufacturing| 2F9-Quality Management for Complaints Against Suppliers",
    "Manufacturing| 2QP-Quality Management of Internal Problems",
    "Manufacturing| 2QW-Analytics for Production Unit - Plan/Actual Production Cost",
    "Manufacturing| 2V0-SAP Fiori Analytical Apps for Quality Management",
    "Manufacturing| 3LO-Change Manufacturing  Bill of Material for Production",
    "Manufacturing| BJ5-Make-to-Stock Production - Discrete Manufacturing ",
    "Manufacturing| BJK-Production Subcontracting - External Processing",
    "Manufacturing| BJN-Rework Processing - Stock-Manufactured Material",
    "Manufacturing| BJQ-Rework Processing - Work-in-Process",
    "Manufacturing| BLF-Batch Management",
    "Manufacturing| BLL-Serial Number Management",
    "Manufacturing| BMY-Subcontracting",
    "Manufacturing| 1NF-Engineering Change Management with Change Records",
    "Manufacturing| 1R3-Engineering Bill of Material - Change Master Management",
    "Manufacturing| 1NR-Engineering Bill of Material - Versions Management",
    "Manufacturing| J44-Material Requirements Planning",
    "Plant Maintenance| BH1-Corrective Maintenance ",
    "Plant Maintenance| BH2-Emergency Maintenance ",
    "Plant Maintenance| BJ2-Preventive Maintenance ",
    "Procurement| 18J-Requisitioning",
    "Procurement| 19E-Supplier Classification and Segmentation",
    "Procurement| 1JI-Real-Time Reporting and Monitoring for Procurement ",
    "Procurement| 1NJ-Responsibility Management",
    "Procurement| 1QR-Predictive Analytics for Purchase Contract Quantity Consumption",
    "Procurement| 1XF-Request for Price",
    "Procurement| 22Z-Procurement  of Services",
    "Procurement| 2QU-Analytics - Purchase Order Visibility and Procurement  Spend",
    "Procurement| 2TX-Direct Procurement  with Inbound Delivery",
    "Procurement| 31N-Situation Handling",
    "Procurement| BMD-Purchase Contract",
    "Procurement| BML-Physical Inventory - Inventory Count and Adjustment",
    "Procurement| BMR-Scheduling Agreements in Procurement ",
    "Procurement| BNX-Consumable Purchasing",
    "Procurement| J45-Procurement  of Direct Materials",
    "Sales Ops| 1F1-Debit Memo Processing",
    "Sales Ops| 2LN-Basic Available-to-Promise Processing",
    "Sales Ops| 2TY-B2B Order Fulfillment with SAP Commerce Cloud",
    "Sales Ops| BD9-Sell from Stock",
    "Sales Ops| BKK-Sales Order Fulfillment Monitoring and Operations",
    "Warehouse| 1FS-Basic Warehouse  Inbound Processing from Supplier",
    "Warehouse| 1FU-Initial Stock Upload for Warehouse ",
    "Warehouse| 1G0-Scrapping in Warehouse ",
    "Warehouse| 1G2-Basic Warehouse  Outbound Processing to Customer",
    "Warehouse| 1V9-Basic Warehouse  Inbound Processing from Supplier with Quality Management",
    "Warehouse| 1VB-Production Integration - Component Consumption and Receipt in Warehouse ",
    "Warehouse| 1VD-Advanced Warehouse  Outbound Processing to Customer",
    "Warehouse| 4LU-Physical Inventory - Cycle Counting",
    "Warehouse| 4MM-Handling Unit Management",
    "Warehouse| BGG-SAP Fiori Analytical Apps for Inventory and Warehouse  Management",
    "Warehouse| BMC-Core Inventory Management",
    "Warehouse| BMK-Return to Supplier",
    "Sourcing and Procurement| BNX-Consumable Purchasing",
    "Sourcing and Procurement| J45-Procurement  of Direct Materials",
    "Supply Chain| 1P7-Cross-Plant Transfer Posting",
    "Supply Chain| 2LN-Basic Available-to-Promise Processing",
    "Supply Chain| 3BR-Warehouse  Inbound Processing",
    "Supply Chain| 3BS-Warehouse  Outbound Processing",
    "Supply Chain| 3BT-Warehouse  Ad Hoc Goods Issue",
    "Supply Chain| 3BU-Warehouse  Posting Changes",
    "Supply Chain| 3BX-Warehouse  Physical Inventory",
    "Supply Chain| 3DV-Warehouse  Production Integration",
    "Supply Chain| 3M0-Quality Management in Warehousing",
    "Supply Chain| 4A2-Replenishment in Warehousing",
    "Supply Chain| 4LU-Physical Inventory - Cycle Counting",
    "Supply Chain| 4MM-Handling Unit Management",
    "Supply Chain| 5HO-Warehouse  Production Integration with Synchronous Goods Receipt",
    "Supply Chain| 63V-Mobile RF Devices in Warehousing",
    "Supply Chain| 63W-Mobile RF Devices in Warehousing with Production Integration",
    "Supply Chain| 63X-Mobile RF Devices in Warehousing with Quality Management",
    "Supply Chain| BGG-SAP Fiori Analytical Apps for Inventory and Warehouse  Management",
    "Supply Chain| BMC-Core Inventory Management",
    "Supply Chain| BMH-Stock Transfer Without Delivery",
    "Supply Chain| BMK-Return to Supplier",
    "Supply Chain| BML-Physical Inventory - Inventory Count and Adjustment",
    "Data Objects in Scope",
    "EWM Product Master",
    "EWM Warehouse  bins",
    "EWM Bin sorting",
    "EWM Fixed bins",
    "EWM Packing Specification",
    "GL Accounts Chart of accounts|",
    "Cost Center",
    "Profit Center",
    "Activity Type",
    "Planned activity price",
    "Bank master",
    "Internal Orders",
    "Supplier bank Data",
    "Fixed Assets",
    "Supplier Master Include Carriers, Farmers & Employees|",
    "Supplier partner function",
    "Material Master - Basic View",
    "Material Master - Alternate UoM",
    "Material Master - Plant Extension",
    "Material Master - Sloc Extension",
    "Create Commodity Codes",
    "Assign Commodity codes",
    "MM Scheduling Agreements",
    "Purchasing Info Records",
    "MM Pricing conditions",
    "Source List",
    "Material Master  Classification include class types 001, 023, 300|",
    "Material Text",
    "Purchasing Text",
    "Batch Master  Template includes batch classification|",
    "Batch Classification",
    "Vendor Master Contact Persons",
    "Purchase Contracts Blanket Pos|",
    "Resources / Work Centers - PM",
    "Equipment Master",
    "Functional Locations",
    "Maintenance  Plan",
    "General Task List",
    "Equipment Task List",
    "Functional Location Task List",
    "Maintenance  Plan Text",
    "Work Centers",
    "Maintenance  Items",
    "Resources / Work Centers - PP",
    "Bill of Materials",
    "Routings",
    "Production Version",
    "Routings - Inspection Characteristics",
    "Routing Component Allocation",
    "Routing Material Assignment",
    "BOM Alternate Item Groups",
    "Resources / WorkCenters",
    "Quality Management Master Inspection Char",
    "Quality Management Master Inspection Method",
    "Material Master - Inspection Type",
    "Material Master - QM View",
    "Quality Management Inspection Plan",
    "Quality Management Level",
    "General Task List",
    "Equipment Task List",
    "Functional Location Task List",
    "Material Master - Sales Org View",
    "Transaction-EWM Inventory Balances",
    "Transaction-Fixed Assets",
    "Transaction-Fixed Asset Balances",
    "Transaction-Accounts Payable Balances",
    "Transaction-GL Balances",
    "Transaction-Inventory Balances cost per unit|",
    "Transaction-Inventory Balances cost per unit and qty by Batch|",
    "Transaction-Open Purchase Orders",
    "Transaction-Open Production Order",
    "Transactional-Sales Order History",
    "Transactional-Production Order History",
    "Transactional-Purchase Order History",
    "WRICEF Objects",
    "RICEF_235 : Failed Output Types Report - EDI and email output failure for purchase orders",
    "RICEF_004: Finance  Inventory Detail View and Extraction",
    "RICEF_252 : Finance  Cost Extraction",
    "RICEF_253 : Finance  GL Extraction",
    "RICEF_119 : BOM reports Place Holder",
    "RICEF_258 : Manufacturing  Component View",
    "RICEF_264 : Manufacturing  Routings View",
    "RICEF_266 : Manufacturing  Serialization View",
    "RICEF_268 : Manufacturing  View & Extraction",
    "RICEF_209 : PO/SO Tracking and Reconciliation Report",
    "RICEF_261 : Manufacturing  Orders Extraction",
    "RICEF_269 : Plant Maintenance  View"
  ],
  "DEPLOY": [
    "Phase Initiation",
    "Solution Cutover Plan",
    "Business Cutover Plan",
    "Execution, Monitoring, and Controlling Results",
    "Data Mapping Documents",
    "Data Extraction and Transformation SAP source|",
    "Data Extraction and Transformation Non-SAP source|",
    "Data Loads into SAP",
    "Data Validation",
    "Setup Operations Control Center",
    "Go / No-Go for Go-Live Decision Check List",
    "Production Cutover – SAP System",
    "Production Cutover – Business and Legacy Systems",
    "Go-Live",
    "Project Phase Closure and Signoff Project Deliverables",
    "Establish Operations Readiness criteria.",
    "Execute Cutover Tasks as per Cutover Plan.",
    "Set Production System to \"Live\".",
    "Define Phase Closure & Sign-Off Process & Criteria.",
    "Training and OCM",
    "Training organized by OCM team",
    "BPOs develop and teach end user trng",
    "BPOs assist end users in change",
    "FCs provide tips and tricks, exception processing",
    "System performance testing",
    "Final Cutover completion Master/Transactional|",
    "All Technical developments complete",
    "Go live support strategy developed by Client",
    "Go live authorization form signed by client",
    "Go Live Date",
    "End-User Training Delivery",
    "Go-Live Authorization",
    "Q-Gate review of Deploy Phase"
  ],
  "RUN": [
    "Issues Resolution",
    "Handover to Application Management",
    "Month-End Close Process",
    "Project Stage I Closure and Signoff Project Phase Deliverables",
    "Establish Hypercare operations.",
    "Establish SAP Support Services connections.",
    "Deploy User Experience Management Tools.",
    "Hypercare complete",
    "Hypercare completion",
    "Q-Gate review of Run Phase",
    "Project Closure and Signoff Project Deliverables"
  ]
}
