task_batches ={
  "Project Management Tools and Templates": [
    "Requirements List",
    "Gaps List",
    "Issue Management Plan and Issues List",
    "Scope Management Plan and Scope Change Templates",
    "Decision Log",
    "Communications Plan",
    "Steering Committee Presentation Templates",
    "High-Level Project Schedule",
    "Project Team Calendar",
    "Task Plan",
    "Individual Work List",
    "Daily Huddle List",
    "WRICEF Tracking Plan",
    "Data Migration Tracking Plan",
    "EDI Tracking",
    "Project Dashboard",
    "Risk Analysis/Mitigation Plan",
    "Testing Strategy Template",
    "Phase Sign-Off Process"
  ],
  "Quality Reviews": [
    "Deliverable Reviews",
    "Q-Gate Reviews"
  ],
  "Data Migration Approach": [
    "Complexity Assessment",
    "Confirm and Plan",
    "Data Mapping",
    "Development",
    "Refine",
    "Extract and Transform",
    "Pre-validation",
    "Load",
    "Post-validation",
    "Correct",
    "Cleanse",
    "Harmonize",
    "Data Cycles"
  ],
  "Embedded Analytics": [
    "Workshops across the various functional areas to help identify out-of-box Embedded Analytics Fiori-based reports to be leveraged.",
    "Identification of potential customizations relative to Fiori reports.",
    "Customization of ten 10 Fiori-based reports."
  ],
  "Analytics: S/4HANA Data Integration to Existing MS Azure based Landscape": [
    "Identify S/4 sources table/views to for use with the current Data Liberator/SLT based integration with the current MS Azure based target database.",
    "Data to be replicated in same manner as ECC",
    "CDS view modification to support replication process as needed.",
    "Provide guidance to Client resources relative to SAP considerations as needed."
  ],
  "SAP Analytics Cloud SAC Implementation w/ or w/out Datasphere DSP": [
    "SAC and DSP tenant set-up as applicable",
    "SAC Cloud Connector/DPA set-up as applicable",
    "Establish required source system integration",
    "Detailed blueprint of solution",
    "DSP and/or SAC based model development to support stories noted below",
    "12 twelve developed stories Dashboard/Visualizations/Excel",
    "Security configuration",
    "Formal system/integration testing"
  ],
  "Technical Development of Workflows, Reports, Interfaces, Conversions, Enhancements, Forms WRICEF and Electronic Data Interface EDI": [
    "Functional specification - Voice of Customer",
    "Agreement on scope for WRICEF object",
    "Unit Test",
    "Final Acceptance Test",
    "Testing"
  ],
  "PREP": [
    "Contract Signature",
    "Standard onboarding activities",
    "Self Enablement",
    "Project Initiation",
    "Project Organization Structure",
    "Project Plan",
    "Project Kickoff and Onboarding",
    "S/4HANA Public Cloud Learning Enablement for Client Team",
    "Project Portal",
    "System Provisioning and Solution Activation",
    "Phase Closure and Signoff Phase Deliverables",
    "Q-Gate review of Prep Phase"
  ],
  "EXPLORE": [
    "Validation",
    "Organization Structure Workshop and Data Education",
    "High Level Value Chain Scenarios",
    "Fit to Standard Workshops",
    "Gap Validation, Finalize Scope, Documentation",
    "Extension and Integration Requirements Gathering",
    "Data Migration Requirements Gathering",
    "Capture requirements in SAP CALM",
    "Fill up Business Driven Configuration Questionnaires",
    "Phase Initiation",
    "Project Team Enablement",
    "Testing Strategy Document",
    "Fit To Standard Workshop",
    "Data Migration Strategy",
    "Extension and Integration Strategy",
    "User Access and Security Strategy",
    "Data Mapping Documents",
    "SAP Development and Test Environment Provisioning",
    "Solution Readout",
    "Phase Closure and Signoff Phase Deliverables",
    "Q-Gate review of Deploy Phase"
  ],
  "REALIZE": [
    "Phase Initiation",
    "Plan Realize Phase",
    "Development Stream Kickoff",
    "Build Cycle Initiation Iterative",
    "Execution, Monitoring and Controlling Results",
    "Configuration",
    "Functional Specifications for In-Scope WRICEF Objects",
    "Technical Specifications for In-Scope WRICEF Objects",
    "Development - WRICEF in SAP",
    "Development - WRICEF in Legacy Systems",
    "Quality Assurance QA Environment Setup",
    "User Experience and Security Kickoff",
    "Test Workstream Kickoff to Support Integration Testing",
    "Define Scope for Entrance and Exit Criteria for the Integration Test Cycle",
    "Test Data Preparation for Integration Test Cycle 1",
    "Test Data Preparation for Additional Integration Tests",
    "Integration Test Execution",
    "Integration Test Signoff",
    "Data Mapping Documents",
    "Data Extraction and Transformation SAP source"
  ],
  "DEPLOY": [
    "Phase Initiation",
    "Solution Cutover Plan",
    "Business Cutover Plan",
    "Execution, Monitoring, and Controlling Results",
    "Data Mapping Documents",
    "Data Extraction and Transformation SAP source",
    "Data Extraction and Transformation Non-SAP source",
    "Data Loads into SAP",
    "Data Validation",
    "Setup Operations Control Center",
    "Go / No-Go for Go-Live Decision Check List",
    "Production Cutover – SAP System",
    "Production Cutover – Business and Legacy Systems",
    "Go-Live",
    "Project Phase Closure and Signoff Project Deliverables",
    "Establish Operations Readiness criteria.",
    "Execute Cutover Tasks as per Cutover Plan.",
    "Set Production System to \"Live\".",
    "Define Phase Closure & Sign-Off Process & Criteria.",
    "Training and OCM"
    ],
  "RUN": [
    "Issues Resolution",
    "Handover to Application Management",
    "Month-End Close Process",
    "Project Stage I Closure and Signoff Project Phase Deliverables",
    "Establish Hypercare operations.",
    "Establish SAP Support Services connections.",
    "Deploy User Experience Management Tools.",
    "Hypercare complete",
    "Hypercare completion",
    "Q-Gate review of Run Phase",
    "Project Closure and Signoff Project Deliverables"
  ]
}